version: 2
jobs:
  build:
    docker:
      - image: docker:git
        environment:
          RSA_PRIVATE_KEY_NAME: sgerrand.rsa
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir packages
      - run: echo -e "$RSA_PUBLIC_KEY" > packages/sgerrand.rsa.pub
      - run: docker run -e RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" -e RSA_PRIVATE_KEY_NAME="sgerrand.rsa" -v $(pwd):/home/builder/package -v $(pwd)/packages:/packages sgerrand/alpine-abuild
      - run: ./bin/citest $(pwd)/packages
      - store_artifacts:
          path: /packages/builder/x86_64/*.apk
    working_directory: /home/builder/package
